services:
  mysql:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 6603:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=root